---
- name: Install Docker
  hosts: localhost
  become: yes

  tasks:
    - name: Remove unnecessary packages
      ansible.builtin.apt:
        name: 
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: yes
        state: present

    - name: Create directory /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Import Docker GPG key
      ansible.builtin.apt_key:
        keyring: /etc/apt/keyrings/docker.gpg
        url: https://download.docker.com/linux/debian/gpg

    - name: Add Docker repository to sources.list.d
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        create: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: yes
        state: latest
